/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.PatientManagement;

/**
 *
 * @author Y4SHVINE
 */
import Controller.PatientManagement.ServiceController;
import Controller.PatientManagement.WardRoundController;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JComboBox;
import model.patientModels.ChanelDoctorModel;
import util.DBUtil;
import static util.DBUtil.LOG;
import util.Util;
import util.Validation;
import util.messageAlert;
public class ChanelDoctor extends javax.swing.JFrame {

    /**
     * Creates new form ChanelDoctor
     */
    public ChanelDoctor() {
        initComponents();
        LOG = org.apache.log4j.Logger.getLogger(ChanelDoctor.class);
        getAllPatientIDs(dcPatientID);
        geDoctorsName(dcDocName);
    }

    private void getAllPatientIDs(JComboBox jc){
        try{
            ServiceController.getInstance().getPatientIDList(jc); 
        }catch(Exception e){
            messageAlert.getMessageAlert(DBUtil.getXMLData("PatientMsg", "message", "Err_Something_Went_Wrong"), "error");
            LOG.error(e);
        }
    }
    
    private static void geDoctorsName(JComboBox jc) {
        try {
            for (Object DocName : WardRoundController.getInstance().getDoctorListDetails()) {
                jc.addItem(DocName);
            }
        } catch (SQLException ex) {
            messageAlert.getMessageAlert(DBUtil.getXMLData("PatientMsg", "message", "Err_Something_Went_Wrong"), "error");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        patientManagementLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        signupFNameLbl1 = new javax.swing.JLabel();
        dcDocName = new javax.swing.JComboBox<>();
        dcChannelSession = new javax.swing.JComboBox<>();
        signupFNameLbl2 = new javax.swing.JLabel();
        cuDate = new javax.swing.JLabel();
        dcChanelDate = new com.toedter.calendar.JDateChooser();
        cuDate1 = new javax.swing.JLabel();
        cdChanelDoctor = new javax.swing.JButton();
        dcPatientID = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 770));
        setMinimumSize(new java.awt.Dimension(900, 770));
        setPreferredSize(new java.awt.Dimension(900, 770));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        patientManagementLbl.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        patientManagementLbl.setForeground(new java.awt.Color(255, 255, 255));
        patientManagementLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientManagementLbl.setText("Doctor Channeling Service");
        jPanel1.add(patientManagementLbl);
        patientManagementLbl.setBounds(0, 10, 900, 60);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setText("Chanel ID");
        jLabel5.setMaximumSize(new java.awt.Dimension(200, 35));
        jLabel5.setMinimumSize(new java.awt.Dimension(200, 35));
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(2280, 450, 200, 35);

        signupFNameLbl1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupFNameLbl1.setForeground(new java.awt.Color(255, 255, 255));
        signupFNameLbl1.setText("Doctor's Name");
        signupFNameLbl1.setMaximumSize(new java.awt.Dimension(200, 35));
        signupFNameLbl1.setMinimumSize(new java.awt.Dimension(200, 35));
        signupFNameLbl1.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(signupFNameLbl1);
        signupFNameLbl1.setBounds(200, 175, 200, 35);

        jPanel1.add(dcDocName);
        dcDocName.setBounds(400, 175, 300, 35);

        dcChannelSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Evening" }));
        jPanel1.add(dcChannelSession);
        dcChannelSession.setBounds(400, 400, 300, 35);

        signupFNameLbl2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupFNameLbl2.setForeground(new java.awt.Color(255, 255, 255));
        signupFNameLbl2.setText("Patient ID");
        signupFNameLbl2.setMaximumSize(new java.awt.Dimension(200, 35));
        signupFNameLbl2.setMinimumSize(new java.awt.Dimension(200, 35));
        signupFNameLbl2.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(signupFNameLbl2);
        signupFNameLbl2.setBounds(200, 250, 200, 35);

        cuDate.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        cuDate.setForeground(new java.awt.Color(255, 255, 255));
        cuDate.setText("Chanel Date");
        cuDate.setMaximumSize(new java.awt.Dimension(200, 35));
        cuDate.setMinimumSize(new java.awt.Dimension(200, 35));
        cuDate.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(cuDate);
        cuDate.setBounds(200, 325, 200, 35);

        dcChanelDate.setMinSelectableDate(new Date());
        jPanel1.add(dcChanelDate);
        dcChanelDate.setBounds(400, 325, 300, 35);

        cuDate1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        cuDate1.setForeground(new java.awt.Color(255, 255, 255));
        cuDate1.setText("Chanel Session");
        cuDate1.setMaximumSize(new java.awt.Dimension(200, 35));
        cuDate1.setMinimumSize(new java.awt.Dimension(200, 35));
        cuDate1.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(cuDate1);
        cuDate1.setBounds(200, 400, 200, 35);

        cdChanelDoctor.setForeground(new java.awt.Color(0, 0, 0));
        cdChanelDoctor.setText("Chanel");
        cdChanelDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdChanelDoctorActionPerformed(evt);
            }
        });
        jPanel1.add(cdChanelDoctor);
        cdChanelDoctor.setBounds(400, 475, 200, 35);

        jPanel1.add(dcPatientID);
        dcPatientID.setBounds(400, 250, 300, 35);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdChanelDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdChanelDoctorActionPerformed
        try{
            if(dcChanelDate.getDate() != null){
                ChanelDoctorModel cd = new ChanelDoctorModel(
                        dcDocName.getSelectedItem().toString(),
                        dcPatientID.getSelectedItem().toString(),
                        Util.convertUtilDateToSqlDate(dcChanelDate.getDate()),
                        dcChannelSession.getSelectedItem().toString()
                );
                if (ServiceController.getInstance().ChannelDoctorService(cd)==true) {
                    messageAlert.getMessageAlert(DBUtil.getXMLData("PatientMsg", "message", "Msg_Succesfully_Added"), "success");
                } else {
                    messageAlert.getMessageAlert(DBUtil.getXMLData("PatientMsg", "message", "Err_Something_Went_Wrong"), "error");
                }
            }
            else{
                messageAlert.getMessageAlert(DBUtil.getXMLData("PatientMsg", "message", "Err_Can_not_Have_Empty_Fields"), "error");
            }
        }catch(Exception ex){
            messageAlert.getMessageAlert(DBUtil.getXMLData("PatientMsg", "message", "Err_Something_Went_Wrong"), "error");
            LOG.error(ex);
        }
    }//GEN-LAST:event_cdChanelDoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChanelDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChanelDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChanelDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChanelDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChanelDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cdChanelDoctor;
    private javax.swing.JLabel cuDate;
    private javax.swing.JLabel cuDate1;
    private com.toedter.calendar.JDateChooser dcChanelDate;
    private javax.swing.JComboBox<String> dcChannelSession;
    private javax.swing.JComboBox<String> dcDocName;
    private javax.swing.JComboBox<String> dcPatientID;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel patientManagementLbl;
    private javax.swing.JLabel signupFNameLbl1;
    private javax.swing.JLabel signupFNameLbl2;
    // End of variables declaration//GEN-END:variables
}
