/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.PatientManagement;

import Controller.PatientManagement.PatientController;
import java.sql.SQLException;
import model.Patient;
import util.Validation;

/**
 *
 * @author Y4SHVINE
 */
public class PatientManaging extends javax.swing.JFrame {

    /**
     * Creates new form PatientSignUp
     */
    public PatientManaging() {
        initComponents();
        fNameErrorIcon.setVisible(false);
        lNameErrorIcon.setVisible(false);
        emailErrorIcon.setVisible(false);
        phoneNumberErrorIcon.setVisible(false);
        nicErrorIcon.setVisible(false);

    }
    boolean signupRegisterBtnVali = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientManagementLbl = new javax.swing.JLabel();
        patientManagementTabPane = new javax.swing.JTabbedPane();
        assignMedicalCheckupPanel = new javax.swing.JPanel();
        assignOpperationPanel = new javax.swing.JPanel();
        patientSignUpPanel = new javax.swing.JPanel();
        signupPID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        signupFNameLbl = new javax.swing.JLabel();
        signupPFirstName = new javax.swing.JTextField();
        patientSignUpLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        signupPLastName = new javax.swing.JTextField();
        signupEmailLbl = new javax.swing.JLabel();
        signupPEmail = new javax.swing.JTextField();
        signupDOBLbl = new javax.swing.JLabel();
        signupPDateofBirth = new com.toedter.calendar.JDateChooser();
        signupEmailLbl1 = new javax.swing.JLabel();
        signupPPhoneNumber = new javax.swing.JTextField();
        signupSexlLbl = new javax.swing.JLabel();
        signupPSexCombo = new javax.swing.JComboBox<>();
        signupNICLbl = new javax.swing.JLabel();
        signupPNIC = new javax.swing.JTextField();
        signupPAddress = new javax.swing.JTextField();
        signupAddressLbl = new javax.swing.JLabel();
        signupPCity = new javax.swing.JTextField();
        signupNICLbl2 = new javax.swing.JLabel();
        signupPCode = new javax.swing.JTextField();
        signupCodeLbl = new javax.swing.JLabel();
        signupCodeLbl1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        signupPAdditionalInfo = new javax.swing.JTextArea();
        signupSubmitBtn = new javax.swing.JButton();
        fNameErrorIcon = new javax.swing.JLabel();
        lNameErrorIcon = new javax.swing.JLabel();
        emailErrorIcon = new javax.swing.JLabel();
        nicErrorIcon = new javax.swing.JLabel();
        phoneNumberErrorIcon = new javax.swing.JLabel();
        patientDetailsPanel = new javax.swing.JPanel();
        signupNICLbl1 = new javax.swing.JLabel();
        detailPNIC = new javax.swing.JTextField();
        signupAddressLbl1 = new javax.swing.JLabel();
        detailPAddress = new javax.swing.JTextField();
        detailPCity = new javax.swing.JTextField();
        signupNICLbl3 = new javax.swing.JLabel();
        signupCodeLbl2 = new javax.swing.JLabel();
        detailPCode = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailPAdditionalInfo = new javax.swing.JTextArea();
        signupCodeLbl3 = new javax.swing.JLabel();
        detailPPhoneNumber = new javax.swing.JTextField();
        signupEmailLbl2 = new javax.swing.JLabel();
        signupEmailLbl3 = new javax.swing.JLabel();
        detailPEmail1 = new javax.swing.JTextField();
        detailSexCombo = new javax.swing.JComboBox<>();
        detailPDateofBirth = new com.toedter.calendar.JDateChooser();
        signupDOBLbl1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        detailPLastName = new javax.swing.JTextField();
        signupPFirstName1 = new javax.swing.JTextField();
        signupFNameLbl1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        detailPID = new javax.swing.JLabel();
        patientSignUpLbl1 = new javax.swing.JLabel();
        detailsSubmitBtn = new javax.swing.JButton();
        detailReportBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        detailPFirstName = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        detailPatientTable = new javax.swing.JTable();
        signupEmailLbl4 = new javax.swing.JLabel();
        detailEditBtn = new javax.swing.JButton();
        patientFoodPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        foodDiatType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        foodPatientID = new javax.swing.JLabel();
        foodDStartDate = new com.toedter.calendar.JDateChooser();
        signupDOBLbl2 = new javax.swing.JLabel();
        signupDOBLbl3 = new javax.swing.JLabel();
        foodDEndDate = new com.toedter.calendar.JDateChooser();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        foodEditBtn = new javax.swing.JButton();
        foodAddBtn = new javax.swing.JButton();
        foodChangeBtn = new javax.swing.JButton();
        patientSignUpLbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1765, 770));
        setMinimumSize(new java.awt.Dimension(1765, 770));
        setPreferredSize(new java.awt.Dimension(1765, 770));
        setResizable(false);
        getContentPane().setLayout(null);

        patientManagementLbl.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        patientManagementLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientManagementLbl.setText("Patient Management");
        getContentPane().add(patientManagementLbl);
        patientManagementLbl.setBounds(10, 20, 1740, 60);

        assignMedicalCheckupPanel.setLayout(null);
        patientManagementTabPane.addTab("Assign for Medical Checkups", assignMedicalCheckupPanel);

        assignOpperationPanel.setLayout(null);
        patientManagementTabPane.addTab("Assign for Operations", assignOpperationPanel);

        patientSignUpPanel.setLayout(null);

        signupPID.setText("1");
        signupPID.setMaximumSize(new java.awt.Dimension(200, 35));
        signupPID.setMinimumSize(new java.awt.Dimension(200, 35));
        signupPID.setPreferredSize(new java.awt.Dimension(200, 35));
        patientSignUpPanel.add(signupPID);
        signupPID.setBounds(300, 75, 300, 35);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setText("Patient ID");
        jLabel4.setMaximumSize(new java.awt.Dimension(200, 35));
        jLabel4.setMinimumSize(new java.awt.Dimension(200, 35));
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 35));
        patientSignUpPanel.add(jLabel4);
        jLabel4.setBounds(100, 75, 200, 35);

        signupFNameLbl.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupFNameLbl.setText("First Name");
        signupFNameLbl.setMaximumSize(new java.awt.Dimension(200, 35));
        signupFNameLbl.setMinimumSize(new java.awt.Dimension(200, 35));
        signupFNameLbl.setPreferredSize(new java.awt.Dimension(200, 35));
        patientSignUpPanel.add(signupFNameLbl);
        signupFNameLbl.setBounds(100, 150, 200, 35);

        signupPFirstName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        signupPFirstName.setMaximumSize(new java.awt.Dimension(200, 35));
        signupPFirstName.setMinimumSize(new java.awt.Dimension(200, 35));
        signupPFirstName.setPreferredSize(new java.awt.Dimension(200, 35));
        signupPFirstName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                signupPFirstNameCaretUpdate(evt);
            }
        });
        patientSignUpPanel.add(signupPFirstName);
        signupPFirstName.setBounds(300, 150, 300, 35);

        patientSignUpLbl.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        patientSignUpLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientSignUpLbl.setText("Patient Registration");
        patientSignUpPanel.add(patientSignUpLbl);
        patientSignUpLbl.setBounds(100, 0, 1530, 50);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setText("Last Name");
        jLabel3.setMaximumSize(new java.awt.Dimension(200, 35));
        jLabel3.setMinimumSize(new java.awt.Dimension(200, 35));
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 35));
        patientSignUpPanel.add(jLabel3);
        jLabel3.setBounds(100, 225, 200, 35);

        signupPLastName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        signupPLastName.setMaximumSize(new java.awt.Dimension(200, 35));
        signupPLastName.setMinimumSize(new java.awt.Dimension(200, 35));
        signupPLastName.setPreferredSize(new java.awt.Dimension(200, 35));
        signupPLastName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                signupPLastNameCaretUpdate(evt);
            }
        });
        patientSignUpPanel.add(signupPLastName);
        signupPLastName.setBounds(300, 225, 300, 35);

        signupEmailLbl.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupEmailLbl.setText("Email");
        signupEmailLbl.setMaximumSize(new java.awt.Dimension(200, 35));
        signupEmailLbl.setMinimumSize(new java.awt.Dimension(200, 35));
        signupEmailLbl.setPreferredSize(new java.awt.Dimension(200, 35));
        patientSignUpPanel.add(signupEmailLbl);
        signupEmailLbl.setBounds(100, 450, 200, 35);

        signupPEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        signupPEmail.setMaximumSize(new java.awt.Dimension(200, 35));
        signupPEmail.setMinimumSize(new java.awt.Dimension(200, 35));
        signupPEmail.setPreferredSize(new java.awt.Dimension(200, 35));
        patientSignUpPanel.add(signupPEmail);
        signupPEmail.setBounds(300, 450, 300, 35);

        signupDOBLbl.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupDOBLbl.setText("Date of Birth");
        signupDOBLbl.setMaximumSize(new java.awt.Dimension(200, 35));
        signupDOBLbl.setMinimumSize(new java.awt.Dimension(200, 35));
        signupDOBLbl.setPreferredSize(new java.awt.Dimension(200, 35));
        patientSignUpPanel.add(signupDOBLbl);
        signupDOBLbl.setBounds(100, 300, 200, 35);
        patientSignUpPanel.add(signupPDateofBirth);
        signupPDateofBirth.setBounds(300, 300, 300, 35);

        signupEmailLbl1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupEmailLbl1.setText("Phone Number");
        signupEmailLbl1.setMaximumSize(new java.awt.Dimension(200, 35));
        signupEmailLbl1.setMinimumSize(new java.awt.Dimension(200, 35));
        signupEmailLbl1.setPreferredSize(new java.awt.Dimension(200, 35));
        patientSignUpPanel.add(signupEmailLbl1);
        signupEmailLbl1.setBounds(100, 525, 200, 35);

        signupPPhoneNumber.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        signupPPhoneNumber.setMaximumSize(new java.awt.Dimension(200, 35));
        signupPPhoneNumber.setMinimumSize(new java.awt.Dimension(200, 35));
        signupPPhoneNumber.setPreferredSize(new java.awt.Dimension(200, 35));
        signupPPhoneNumber.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                signupPPhoneNumberCaretUpdate(evt);
            }
        });
        patientSignUpPanel.add(signupPPhoneNumber);
        signupPPhoneNumber.setBounds(300, 525, 300, 35);

        signupSexlLbl.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupSexlLbl.setText("Sex");
        signupSexlLbl.setMaximumSize(new java.awt.Dimension(200, 35));
        signupSexlLbl.setMinimumSize(new java.awt.Dimension(200, 35));
        signupSexlLbl.setPreferredSize(new java.awt.Dimension(200, 35));
        patientSignUpPanel.add(signupSexlLbl);
        signupSexlLbl.setBounds(100, 375, 200, 35);

        signupPSexCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        patientSignUpPanel.add(signupPSexCombo);
        signupPSexCombo.setBounds(300, 375, 300, 35);

        signupNICLbl.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupNICLbl.setText("NIC");
        signupNICLbl.setMaximumSize(new java.awt.Dimension(200, 35));
        signupNICLbl.setMinimumSize(new java.awt.Dimension(200, 35));
        signupNICLbl.setPreferredSize(new java.awt.Dimension(200, 35));
        patientSignUpPanel.add(signupNICLbl);
        signupNICLbl.setBounds(1130, 75, 200, 35);

        signupPNIC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        signupPNIC.setMaximumSize(new java.awt.Dimension(200, 35));
        signupPNIC.setMinimumSize(new java.awt.Dimension(200, 35));
        signupPNIC.setPreferredSize(new java.awt.Dimension(200, 35));
        signupPNIC.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                signupPNICCaretUpdate(evt);
            }
        });
        patientSignUpPanel.add(signupPNIC);
        signupPNIC.setBounds(1330, 75, 300, 35);

        signupPAddress.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        signupPAddress.setMaximumSize(new java.awt.Dimension(200, 35));
        signupPAddress.setMinimumSize(new java.awt.Dimension(200, 35));
        signupPAddress.setPreferredSize(new java.awt.Dimension(200, 35));
        patientSignUpPanel.add(signupPAddress);
        signupPAddress.setBounds(1330, 150, 300, 35);

        signupAddressLbl.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupAddressLbl.setText("Address");
        signupAddressLbl.setMaximumSize(new java.awt.Dimension(200, 35));
        signupAddressLbl.setMinimumSize(new java.awt.Dimension(200, 35));
        signupAddressLbl.setPreferredSize(new java.awt.Dimension(200, 35));
        patientSignUpPanel.add(signupAddressLbl);
        signupAddressLbl.setBounds(1130, 150, 200, 35);

        signupPCity.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        signupPCity.setMaximumSize(new java.awt.Dimension(200, 35));
        signupPCity.setMinimumSize(new java.awt.Dimension(200, 35));
        signupPCity.setPreferredSize(new java.awt.Dimension(200, 35));
        patientSignUpPanel.add(signupPCity);
        signupPCity.setBounds(1330, 225, 300, 35);

        signupNICLbl2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupNICLbl2.setText("City");
        signupNICLbl2.setMaximumSize(new java.awt.Dimension(200, 35));
        signupNICLbl2.setMinimumSize(new java.awt.Dimension(200, 35));
        signupNICLbl2.setPreferredSize(new java.awt.Dimension(200, 35));
        patientSignUpPanel.add(signupNICLbl2);
        signupNICLbl2.setBounds(1130, 225, 200, 35);

        signupPCode.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        signupPCode.setMaximumSize(new java.awt.Dimension(200, 35));
        signupPCode.setMinimumSize(new java.awt.Dimension(200, 35));
        signupPCode.setPreferredSize(new java.awt.Dimension(200, 35));
        patientSignUpPanel.add(signupPCode);
        signupPCode.setBounds(1330, 300, 300, 35);

        signupCodeLbl.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupCodeLbl.setText("Zip / Postal Code");
        signupCodeLbl.setMaximumSize(new java.awt.Dimension(200, 35));
        signupCodeLbl.setMinimumSize(new java.awt.Dimension(200, 35));
        signupCodeLbl.setPreferredSize(new java.awt.Dimension(200, 35));
        patientSignUpPanel.add(signupCodeLbl);
        signupCodeLbl.setBounds(1130, 300, 200, 35);

        signupCodeLbl1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupCodeLbl1.setText("Additional Infomation");
        signupCodeLbl1.setMaximumSize(new java.awt.Dimension(200, 35));
        signupCodeLbl1.setMinimumSize(new java.awt.Dimension(200, 35));
        signupCodeLbl1.setPreferredSize(new java.awt.Dimension(200, 35));
        patientSignUpPanel.add(signupCodeLbl1);
        signupCodeLbl1.setBounds(1130, 375, 200, 35);

        signupPAdditionalInfo.setColumns(20);
        signupPAdditionalInfo.setRows(5);
        jScrollPane1.setViewportView(signupPAdditionalInfo);

        patientSignUpPanel.add(jScrollPane1);
        jScrollPane1.setBounds(1330, 370, 300, 190);

        signupSubmitBtn.setText("Submit");
        signupSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupSubmitBtnActionPerformed(evt);
            }
        });
        patientSignUpPanel.add(signupSubmitBtn);
        signupSubmitBtn.setBounds(750, 560, 200, 35);

        fNameErrorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/common/Wrong.png"))); // NOI18N
        patientSignUpPanel.add(fNameErrorIcon);
        fNameErrorIcon.setBounds(610, 150, 15, 35);

        lNameErrorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/common/Wrong.png"))); // NOI18N
        patientSignUpPanel.add(lNameErrorIcon);
        lNameErrorIcon.setBounds(610, 225, 15, 35);

        emailErrorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/common/Wrong.png"))); // NOI18N
        patientSignUpPanel.add(emailErrorIcon);
        emailErrorIcon.setBounds(610, 450, 15, 35);

        nicErrorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/common/Wrong.png"))); // NOI18N
        patientSignUpPanel.add(nicErrorIcon);
        nicErrorIcon.setBounds(1640, 75, 15, 35);

        phoneNumberErrorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/common/Wrong.png"))); // NOI18N
        patientSignUpPanel.add(phoneNumberErrorIcon);
        phoneNumberErrorIcon.setBounds(610, 525, 15, 35);

        patientManagementTabPane.addTab("Patient SignUp", patientSignUpPanel);

        patientDetailsPanel.setLayout(null);

        signupNICLbl1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupNICLbl1.setText("NIC");
        signupNICLbl1.setMaximumSize(new java.awt.Dimension(200, 35));
        signupNICLbl1.setMinimumSize(new java.awt.Dimension(200, 35));
        signupNICLbl1.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(signupNICLbl1);
        signupNICLbl1.setBounds(890, 150, 200, 35);

        detailPNIC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        detailPNIC.setMaximumSize(new java.awt.Dimension(200, 35));
        detailPNIC.setMinimumSize(new java.awt.Dimension(200, 35));
        detailPNIC.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(detailPNIC);
        detailPNIC.setBounds(1090, 150, 300, 35);

        signupAddressLbl1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupAddressLbl1.setText("Address");
        signupAddressLbl1.setMaximumSize(new java.awt.Dimension(200, 35));
        signupAddressLbl1.setMinimumSize(new java.awt.Dimension(200, 35));
        signupAddressLbl1.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(signupAddressLbl1);
        signupAddressLbl1.setBounds(890, 200, 200, 35);

        detailPAddress.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        detailPAddress.setMaximumSize(new java.awt.Dimension(200, 35));
        detailPAddress.setMinimumSize(new java.awt.Dimension(200, 35));
        detailPAddress.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(detailPAddress);
        detailPAddress.setBounds(1090, 200, 300, 35);

        detailPCity.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        detailPCity.setMaximumSize(new java.awt.Dimension(200, 35));
        detailPCity.setMinimumSize(new java.awt.Dimension(200, 35));
        detailPCity.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(detailPCity);
        detailPCity.setBounds(1090, 250, 300, 35);

        signupNICLbl3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupNICLbl3.setText("City");
        signupNICLbl3.setMaximumSize(new java.awt.Dimension(200, 35));
        signupNICLbl3.setMinimumSize(new java.awt.Dimension(200, 35));
        signupNICLbl3.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(signupNICLbl3);
        signupNICLbl3.setBounds(890, 250, 200, 35);

        signupCodeLbl2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupCodeLbl2.setText("Zip / Postal Code");
        signupCodeLbl2.setMaximumSize(new java.awt.Dimension(200, 35));
        signupCodeLbl2.setMinimumSize(new java.awt.Dimension(200, 35));
        signupCodeLbl2.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(signupCodeLbl2);
        signupCodeLbl2.setBounds(890, 300, 200, 35);

        detailPCode.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        detailPCode.setMaximumSize(new java.awt.Dimension(200, 35));
        detailPCode.setMinimumSize(new java.awt.Dimension(200, 35));
        detailPCode.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(detailPCode);
        detailPCode.setBounds(1090, 300, 300, 35);

        detailPAdditionalInfo.setColumns(20);
        detailPAdditionalInfo.setRows(5);
        jScrollPane2.setViewportView(detailPAdditionalInfo);

        patientDetailsPanel.add(jScrollPane2);
        jScrollPane2.setBounds(1090, 350, 300, 70);

        signupCodeLbl3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupCodeLbl3.setText("Additional Infomation");
        signupCodeLbl3.setMaximumSize(new java.awt.Dimension(200, 35));
        signupCodeLbl3.setMinimumSize(new java.awt.Dimension(200, 35));
        signupCodeLbl3.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(signupCodeLbl3);
        signupCodeLbl3.setBounds(890, 350, 200, 35);

        detailPPhoneNumber.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        detailPPhoneNumber.setMaximumSize(new java.awt.Dimension(200, 35));
        detailPPhoneNumber.setMinimumSize(new java.awt.Dimension(200, 35));
        detailPPhoneNumber.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(detailPPhoneNumber);
        detailPPhoneNumber.setBounds(1090, 100, 300, 35);

        signupEmailLbl2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupEmailLbl2.setText("Phone Number");
        signupEmailLbl2.setMaximumSize(new java.awt.Dimension(200, 35));
        signupEmailLbl2.setMinimumSize(new java.awt.Dimension(200, 35));
        signupEmailLbl2.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(signupEmailLbl2);
        signupEmailLbl2.setBounds(890, 100, 200, 35);

        signupEmailLbl3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupEmailLbl3.setText("Email");
        signupEmailLbl3.setMaximumSize(new java.awt.Dimension(200, 35));
        signupEmailLbl3.setMinimumSize(new java.awt.Dimension(200, 35));
        signupEmailLbl3.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(signupEmailLbl3);
        signupEmailLbl3.setBounds(100, 350, 200, 35);

        detailPEmail1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        detailPEmail1.setMaximumSize(new java.awt.Dimension(200, 35));
        detailPEmail1.setMinimumSize(new java.awt.Dimension(200, 35));
        detailPEmail1.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(detailPEmail1);
        detailPEmail1.setBounds(300, 350, 300, 35);

        detailSexCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        patientDetailsPanel.add(detailSexCombo);
        detailSexCombo.setBounds(300, 300, 300, 35);
        patientDetailsPanel.add(detailPDateofBirth);
        detailPDateofBirth.setBounds(300, 250, 300, 35);

        signupDOBLbl1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupDOBLbl1.setText("Date of Birth");
        signupDOBLbl1.setMaximumSize(new java.awt.Dimension(200, 35));
        signupDOBLbl1.setMinimumSize(new java.awt.Dimension(200, 35));
        signupDOBLbl1.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(signupDOBLbl1);
        signupDOBLbl1.setBounds(100, 250, 200, 35);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setText("Last Name");
        jLabel5.setMaximumSize(new java.awt.Dimension(200, 35));
        jLabel5.setMinimumSize(new java.awt.Dimension(200, 35));
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(jLabel5);
        jLabel5.setBounds(100, 200, 200, 35);

        detailPLastName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        detailPLastName.setMaximumSize(new java.awt.Dimension(200, 35));
        detailPLastName.setMinimumSize(new java.awt.Dimension(200, 35));
        detailPLastName.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(detailPLastName);
        detailPLastName.setBounds(300, 200, 300, 35);

        signupPFirstName1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        signupPFirstName1.setMaximumSize(new java.awt.Dimension(200, 35));
        signupPFirstName1.setMinimumSize(new java.awt.Dimension(200, 35));
        signupPFirstName1.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(signupPFirstName1);
        signupPFirstName1.setBounds(300, 50, 200, 35);

        signupFNameLbl1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupFNameLbl1.setText("First Name");
        signupFNameLbl1.setMaximumSize(new java.awt.Dimension(200, 35));
        signupFNameLbl1.setMinimumSize(new java.awt.Dimension(200, 35));
        signupFNameLbl1.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(signupFNameLbl1);
        signupFNameLbl1.setBounds(100, 150, 200, 35);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setText("Patient ID");
        jLabel6.setMaximumSize(new java.awt.Dimension(200, 35));
        jLabel6.setMinimumSize(new java.awt.Dimension(200, 35));
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(jLabel6);
        jLabel6.setBounds(100, 100, 200, 35);

        detailPID.setText("ID");
        detailPID.setMaximumSize(new java.awt.Dimension(200, 35));
        detailPID.setMinimumSize(new java.awt.Dimension(200, 35));
        detailPID.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(detailPID);
        detailPID.setBounds(300, 100, 300, 35);

        patientSignUpLbl1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        patientSignUpLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientSignUpLbl1.setText("Patient Details");
        patientDetailsPanel.add(patientSignUpLbl1);
        patientSignUpLbl1.setBounds(100, 0, 1550, 50);

        detailsSubmitBtn.setText("Submit");
        patientDetailsPanel.add(detailsSubmitBtn);
        detailsSubmitBtn.setBounds(1450, 200, 200, 35);

        detailReportBtn.setText("Reorts");
        patientDetailsPanel.add(detailReportBtn);
        detailReportBtn.setBounds(1450, 300, 200, 35);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setText("Name or Patient ID");
        jLabel7.setMaximumSize(new java.awt.Dimension(200, 35));
        jLabel7.setMinimumSize(new java.awt.Dimension(200, 35));
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(jLabel7);
        jLabel7.setBounds(100, 50, 200, 35);

        detailPFirstName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        detailPFirstName.setMaximumSize(new java.awt.Dimension(200, 35));
        detailPFirstName.setMinimumSize(new java.awt.Dimension(200, 35));
        detailPFirstName.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(detailPFirstName);
        detailPFirstName.setBounds(300, 150, 300, 35);

        jButton3.setText("Search");
        patientDetailsPanel.add(jButton3);
        jButton3.setBounds(500, 50, 100, 35);

        detailPatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient ID", "First Name", "Last Name", "Sex"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(detailPatientTable);

        patientDetailsPanel.add(jScrollPane3);
        jScrollPane3.setBounds(90, 430, 1300, 180);

        signupEmailLbl4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupEmailLbl4.setText("Sex");
        signupEmailLbl4.setMaximumSize(new java.awt.Dimension(200, 35));
        signupEmailLbl4.setMinimumSize(new java.awt.Dimension(200, 35));
        signupEmailLbl4.setPreferredSize(new java.awt.Dimension(200, 35));
        patientDetailsPanel.add(signupEmailLbl4);
        signupEmailLbl4.setBounds(100, 300, 200, 35);

        detailEditBtn.setText("Edit");
        patientDetailsPanel.add(detailEditBtn);
        detailEditBtn.setBounds(1450, 100, 200, 35);

        patientManagementTabPane.addTab("Patient Details and Reports", patientDetailsPanel);

        patientFoodPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setText("Patient ID or Name");
        patientFoodPanel.add(jLabel1);
        jLabel1.setBounds(100, 75, 200, 35);
        patientFoodPanel.add(jTextField1);
        jTextField1.setBounds(300, 75, 200, 35);

        jButton1.setText("Search");
        patientFoodPanel.add(jButton1);
        jButton1.setBounds(500, 75, 100, 35);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setText("Diat Type");
        patientFoodPanel.add(jLabel2);
        jLabel2.setBounds(100, 225, 200, 35);

        foodDiatType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        patientFoodPanel.add(foodDiatType);
        foodDiatType.setBounds(300, 225, 300, 35);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setText("Patient ID ");
        patientFoodPanel.add(jLabel8);
        jLabel8.setBounds(100, 150, 200, 35);

        foodPatientID.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        foodPatientID.setText("Patient ID ");
        patientFoodPanel.add(foodPatientID);
        foodPatientID.setBounds(300, 150, 200, 35);
        patientFoodPanel.add(foodDStartDate);
        foodDStartDate.setBounds(940, 150, 300, 35);

        signupDOBLbl2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupDOBLbl2.setText("Start Date");
        signupDOBLbl2.setMaximumSize(new java.awt.Dimension(200, 35));
        signupDOBLbl2.setMinimumSize(new java.awt.Dimension(200, 35));
        signupDOBLbl2.setPreferredSize(new java.awt.Dimension(200, 35));
        patientFoodPanel.add(signupDOBLbl2);
        signupDOBLbl2.setBounds(740, 150, 200, 35);

        signupDOBLbl3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupDOBLbl3.setText("End Date");
        signupDOBLbl3.setMaximumSize(new java.awt.Dimension(200, 35));
        signupDOBLbl3.setMinimumSize(new java.awt.Dimension(200, 35));
        signupDOBLbl3.setPreferredSize(new java.awt.Dimension(200, 35));
        patientFoodPanel.add(signupDOBLbl3);
        signupDOBLbl3.setBounds(740, 225, 200, 35);
        patientFoodPanel.add(foodDEndDate);
        foodDEndDate.setBounds(940, 225, 300, 35);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "First Name", "Last Name", "Diat Type", "Start Date", "End Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable1);

        patientFoodPanel.add(jScrollPane4);
        jScrollPane4.setBounds(100, 300, 1520, 270);

        foodEditBtn.setText("Edit");
        patientFoodPanel.add(foodEditBtn);
        foodEditBtn.setBounds(1410, 150, 100, 35);

        foodAddBtn.setText("Add");
        patientFoodPanel.add(foodAddBtn);
        foodAddBtn.setBounds(1410, 225, 200, 35);

        foodChangeBtn.setText("Change");
        patientFoodPanel.add(foodChangeBtn);
        foodChangeBtn.setBounds(1510, 150, 100, 35);

        patientSignUpLbl2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        patientSignUpLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientSignUpLbl2.setText("Patient - Food Management");
        patientFoodPanel.add(patientSignUpLbl2);
        patientSignUpLbl2.setBounds(100, 0, 1510, 50);

        patientManagementTabPane.addTab("Patient - Food Management", patientFoodPanel);

        getContentPane().add(patientManagementTabPane);
        patientManagementTabPane.setBounds(10, 90, 1740, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupSubmitBtnActionPerformed
        if (signupRegisterBtnVali != false) {
            try {
                Patient patient = new Patient(
                        signupPID.getText(),
                        signupPFirstName.getText(),
                        signupPLastName.getText(),
                        signupPSexCombo.getSelectedItem().toString(),
                        signupPEmail.getText(),
                        signupPPhoneNumber.getText(),
                        signupPNIC.getText(),
                        signupPAddress.getText(),
                        signupPCity.getText(),
                        signupPCode.getText(),
                        signupPAdditionalInfo.getText(),
                        Validation.convertUtilDateToSqlDate(signupPDateofBirth.getDate())
                );
                PatientController.getInstance().patientSignUp(patient);
            } catch (SQLException e) {
                System.out.println("view.PatientManagement.PatientManaging.signupSubmitBtnActionPerformed() error" + e);
            }
        } else {
            System.out.println("Invalide fieldes");
        }

    }//GEN-LAST:event_signupSubmitBtnActionPerformed

    private void signupPFirstNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_signupPFirstNameCaretUpdate
        if (!"".equals(signupPFirstName.getText())) {
            boolean fNameVali = Validation.ContainOnlyLetters(signupPFirstName.getText());
            if (fNameVali == false) {
                fNameErrorIcon.setVisible(true);
                signupRegisterBtnVali = false;
            } else {
                fNameErrorIcon.setVisible(false);
                signupRegisterBtnVali = true;
            }
        }
    }//GEN-LAST:event_signupPFirstNameCaretUpdate

    private void signupPLastNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_signupPLastNameCaretUpdate
        if (!"".equals(signupPLastName.getText())) {
            boolean lNameVali = Validation.ContainOnlyLetters(signupPLastName.getText());
            if (lNameVali == false) {
                lNameErrorIcon.setVisible(true);
                signupRegisterBtnVali = false;
            } else {
                lNameErrorIcon.setVisible(false);
                signupRegisterBtnVali = true;
            }
        }
    }//GEN-LAST:event_signupPLastNameCaretUpdate

    private void signupPPhoneNumberCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_signupPPhoneNumberCaretUpdate
        if (!"".equals(signupPPhoneNumber.getText())) {
            boolean phoneNumberVali = Validation.isAcceptableContactNumber(signupPPhoneNumber.getText());
            if (phoneNumberVali == false) {
                phoneNumberErrorIcon.setVisible(true);
                signupRegisterBtnVali = false;
            } else {
                phoneNumberErrorIcon.setVisible(false);
                signupRegisterBtnVali = true;
            }
        }
    }//GEN-LAST:event_signupPPhoneNumberCaretUpdate

    private void signupPNICCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_signupPNICCaretUpdate
        if (!"".equals(signupPNIC.getText())) {
            boolean phoneNumberVali = Validation.isAcceptableNIC(signupPNIC.getText());
            if (phoneNumberVali == false) {
                nicErrorIcon.setVisible(true);
                signupRegisterBtnVali = false;
            } else {
                nicErrorIcon.setVisible(false);
                signupRegisterBtnVali = true;
            }
        }
    }//GEN-LAST:event_signupPNICCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientManaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientManaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientManaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientManaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientManaging().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel assignMedicalCheckupPanel;
    private javax.swing.JPanel assignOpperationPanel;
    private javax.swing.JButton detailEditBtn;
    private javax.swing.JTextArea detailPAdditionalInfo;
    private javax.swing.JTextField detailPAddress;
    private javax.swing.JTextField detailPCity;
    private javax.swing.JTextField detailPCode;
    private com.toedter.calendar.JDateChooser detailPDateofBirth;
    private javax.swing.JTextField detailPEmail1;
    private javax.swing.JTextField detailPFirstName;
    private javax.swing.JLabel detailPID;
    private javax.swing.JTextField detailPLastName;
    private javax.swing.JTextField detailPNIC;
    private javax.swing.JTextField detailPPhoneNumber;
    private javax.swing.JTable detailPatientTable;
    private javax.swing.JButton detailReportBtn;
    private javax.swing.JComboBox<String> detailSexCombo;
    private javax.swing.JButton detailsSubmitBtn;
    private javax.swing.JLabel emailErrorIcon;
    private javax.swing.JLabel fNameErrorIcon;
    private javax.swing.JButton foodAddBtn;
    private javax.swing.JButton foodChangeBtn;
    private com.toedter.calendar.JDateChooser foodDEndDate;
    private com.toedter.calendar.JDateChooser foodDStartDate;
    private javax.swing.JComboBox<String> foodDiatType;
    private javax.swing.JButton foodEditBtn;
    private javax.swing.JLabel foodPatientID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lNameErrorIcon;
    private javax.swing.JLabel nicErrorIcon;
    private javax.swing.JPanel patientDetailsPanel;
    private javax.swing.JPanel patientFoodPanel;
    private javax.swing.JLabel patientManagementLbl;
    private javax.swing.JTabbedPane patientManagementTabPane;
    private javax.swing.JLabel patientSignUpLbl;
    private javax.swing.JLabel patientSignUpLbl1;
    private javax.swing.JLabel patientSignUpLbl2;
    private javax.swing.JPanel patientSignUpPanel;
    private javax.swing.JLabel phoneNumberErrorIcon;
    private javax.swing.JLabel signupAddressLbl;
    private javax.swing.JLabel signupAddressLbl1;
    private javax.swing.JLabel signupCodeLbl;
    private javax.swing.JLabel signupCodeLbl1;
    private javax.swing.JLabel signupCodeLbl2;
    private javax.swing.JLabel signupCodeLbl3;
    private javax.swing.JLabel signupDOBLbl;
    private javax.swing.JLabel signupDOBLbl1;
    private javax.swing.JLabel signupDOBLbl2;
    private javax.swing.JLabel signupDOBLbl3;
    private javax.swing.JLabel signupEmailLbl;
    private javax.swing.JLabel signupEmailLbl1;
    private javax.swing.JLabel signupEmailLbl2;
    private javax.swing.JLabel signupEmailLbl3;
    private javax.swing.JLabel signupEmailLbl4;
    private javax.swing.JLabel signupFNameLbl;
    private javax.swing.JLabel signupFNameLbl1;
    private javax.swing.JLabel signupNICLbl;
    private javax.swing.JLabel signupNICLbl1;
    private javax.swing.JLabel signupNICLbl2;
    private javax.swing.JLabel signupNICLbl3;
    private javax.swing.JTextArea signupPAdditionalInfo;
    private javax.swing.JTextField signupPAddress;
    private javax.swing.JTextField signupPCity;
    private javax.swing.JTextField signupPCode;
    private com.toedter.calendar.JDateChooser signupPDateofBirth;
    private javax.swing.JTextField signupPEmail;
    private javax.swing.JTextField signupPFirstName;
    private javax.swing.JTextField signupPFirstName1;
    private javax.swing.JLabel signupPID;
    private javax.swing.JTextField signupPLastName;
    private javax.swing.JTextField signupPNIC;
    private javax.swing.JTextField signupPPhoneNumber;
    private javax.swing.JComboBox<String> signupPSexCombo;
    private javax.swing.JLabel signupSexlLbl;
    private javax.swing.JButton signupSubmitBtn;
    // End of variables declaration//GEN-END:variables
}
