/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.PatientManagement;

import Controller.PatientManagement.WardRoundController;
import java.sql.SQLException;
import java.util.Date;
import java.util.Calendar;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import model.patientModels.wardRound;
import util.DBUtil;
import static util.DBUtil.LOG;
import util.Validation;
import util.messageAlert;

/**
 *
 * @author Y4SHVINE
 */
public class WardRounds extends javax.swing.JFrame {

    /**
     * Creates new form WardRounds
     */
    public WardRounds() {
        initComponents();
        LOG = org.apache.log4j.Logger.getLogger(WardRounds.class);
        geDoctorsName(wrDocName);
        WardRoundController.getInstance().getWardTypeList(wrWardName);
    }

    private static void geDoctorsName(JComboBox jc) {
        try {
            for (Object DocName : WardRoundController.getInstance().getDoctorListDetails()) {
                jc.addItem(DocName);
            }
        } catch (SQLException ex) {
            messageAlert.getMessageAlert(DBUtil.getXMLData("PatientMsg", "message", "Err_Something_Went_Wrong"), "error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        patientManagementLbl = new javax.swing.JLabel();
        signupFNameLbl1 = new javax.swing.JLabel();
        wrDocName = new javax.swing.JComboBox<>();
        signupFNameLbl2 = new javax.swing.JLabel();
        wrWardName = new javax.swing.JComboBox<>();
        wrDate = new com.toedter.calendar.JDateChooser();
        cuDate = new javax.swing.JLabel();
        cuDate1 = new javax.swing.JLabel();
        Date date = new Date();
        SpinnerDateModel sm = new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        wrStartTime = new javax.swing.JSpinner(sm);
        addWardRoundBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 770));
        setMinimumSize(new java.awt.Dimension(900, 770));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        patientManagementLbl.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        patientManagementLbl.setForeground(new java.awt.Color(255, 255, 255));
        patientManagementLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientManagementLbl.setText("Ward Round Scheduling");
        jPanel1.add(patientManagementLbl);
        patientManagementLbl.setBounds(0, 30, 900, 60);

        signupFNameLbl1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupFNameLbl1.setForeground(new java.awt.Color(255, 255, 255));
        signupFNameLbl1.setText("Doctor's Name");
        signupFNameLbl1.setMaximumSize(new java.awt.Dimension(200, 35));
        signupFNameLbl1.setMinimumSize(new java.awt.Dimension(200, 35));
        signupFNameLbl1.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(signupFNameLbl1);
        signupFNameLbl1.setBounds(200, 175, 200, 35);

        jPanel1.add(wrDocName);
        wrDocName.setBounds(400, 175, 300, 35);

        signupFNameLbl2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        signupFNameLbl2.setForeground(new java.awt.Color(255, 255, 255));
        signupFNameLbl2.setText("Ward Name");
        signupFNameLbl2.setMaximumSize(new java.awt.Dimension(200, 35));
        signupFNameLbl2.setMinimumSize(new java.awt.Dimension(200, 35));
        signupFNameLbl2.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(signupFNameLbl2);
        signupFNameLbl2.setBounds(200, 250, 200, 35);

        jPanel1.add(wrWardName);
        wrWardName.setBounds(400, 250, 300, 35);

        wrDate.setMinSelectableDate(new Date());
        jPanel1.add(wrDate);
        wrDate.setBounds(400, 325, 300, 35);

        cuDate.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        cuDate.setForeground(new java.awt.Color(255, 255, 255));
        cuDate.setText("Date");
        cuDate.setMaximumSize(new java.awt.Dimension(200, 35));
        cuDate.setMinimumSize(new java.awt.Dimension(200, 35));
        cuDate.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(cuDate);
        cuDate.setBounds(200, 325, 200, 35);

        cuDate1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        cuDate1.setForeground(new java.awt.Color(255, 255, 255));
        cuDate1.setText("Start Time");
        cuDate1.setMaximumSize(new java.awt.Dimension(200, 35));
        cuDate1.setMinimumSize(new java.awt.Dimension(200, 35));
        cuDate1.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(cuDate1);
        cuDate1.setBounds(200, 400, 200, 35);

        JSpinner.DateEditor de = new JSpinner.DateEditor(wrStartTime, "HH:mm:ss");
        wrStartTime.setEditor(de);
        jPanel1.add(wrStartTime);
        wrStartTime.setBounds(400, 400, 300, 35);

        addWardRoundBtn.setText("Add");
        addWardRoundBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWardRoundBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addWardRoundBtn);
        addWardRoundBtn.setBounds(400, 475, 200, 35);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addWardRoundBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWardRoundBtnActionPerformed
        try {
            if (wrDate.getDate() != null) {
                wardRound wr = new wardRound(
                        wrDocName.getSelectedItem().toString(),
                        wrWardName.getSelectedItem().toString(),
                        Validation.convertUtilDateToSqlDate(wrDate.getDate()),
                        wrStartTime.getValue().toString()
                );
                if (WardRoundController.getInstance().addWardRoundDetails(wr)) {
                    messageAlert.getMessageAlert(DBUtil.getXMLData("PatientMsg", "message", "Msg_Succesfully_Added"), "success");
                } else {
                    messageAlert.getMessageAlert(DBUtil.getXMLData("PatientMsg", "message", "Err_Something_Went_Wrong"), "error");
                }
            } else {
                messageAlert.getMessageAlert(DBUtil.getXMLData("PatientMsg", "message", "Err_Can_not_Have_Empty_Fields"), "error");
            }

        } catch (Exception ex) {
            messageAlert.getMessageAlert(DBUtil.getXMLData("PatientMsg", "message", "Err_Something_Went_Wrong"), "error");
            LOG.error(ex);
        }
    }//GEN-LAST:event_addWardRoundBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WardRounds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WardRounds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WardRounds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WardRounds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WardRounds().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addWardRoundBtn;
    private javax.swing.JLabel cuDate;
    private javax.swing.JLabel cuDate1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel patientManagementLbl;
    private javax.swing.JLabel signupFNameLbl1;
    private javax.swing.JLabel signupFNameLbl2;
    private com.toedter.calendar.JDateChooser wrDate;
    private javax.swing.JComboBox<String> wrDocName;
    private javax.swing.JSpinner wrStartTime;
    private javax.swing.JComboBox<String> wrWardName;
    // End of variables declaration//GEN-END:variables
}
