/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.PrescriptionManagement;

import Controller.PrescriptionManagement.PrescriptionController;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.Prescription;
import org.apache.log4j.Logger;
import util.Config;

/**
 *
 * @author hp
 */
public class PrescView extends javax.swing.JFrame {

    int patientId;
    Config cnf = new Config();
    public Logger LOG;

    DefaultTableModel model;
    int selectIndex;
    PrescriptionController pctrl = new PrescriptionController();
    /**
     * Creates new form PrescView
     */
    
    public PrescView() throws IOException {
        initComponents();
        viewtableload(pctrl.allPrescViewData());
        drugtableload(pctrl.viewAllDrugData());
    }
    
    private List<Prescription> searchResultList;
    private List<Prescription> drugSearchResults;
    
    public void viewtableload(ArrayList<Prescription> dataView){
        
        try {
             
           // model = (DefaultTableModel) prescriptionTable.getModel();
           // model.getDataVector().removeAllElements();
           // model.fireTableDataChanged();

            //Object[] row = new Object[10];
            //Prescription dataList = new Prescription();
            
            
            model = (DefaultTableModel) prescTable.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            
           Object[] row = new Object[4];

     
            
           //ArrayList<Prescription> AR = PrescriptionController.getPresc().getAllPrescriptionData();
           
            for (int i = 0; i < dataView.size(); i++) {
                
                row[0]= dataView.get(i).getPrescriptionID();
                row[1] = dataView.get(i).getPatientName();
                row[2] = dataView.get(i).getAge();
                row[3] = dataView.get(i).getCreateDate();
                                
                model.addRow(row);
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }
    
    public void drugtableload(ArrayList<Prescription> viewDrug){
        
        try {
             
           // model = (DefaultTableModel) prescriptionTable.getModel();
           // model.getDataVector().removeAllElements();
           // model.fireTableDataChanged();

            //Object[] row = new Object[10];
            //Prescription dataList = new Prescription();
            
            
            model = (DefaultTableModel) drugTable.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            
           Object[] row = new Object[5];

     
            
           //ArrayList<Prescription> AR = PrescriptionController.getPresc().getAllPrescriptionData();
           
            for (int i = 0; i < viewDrug.size(); i++) {
                
                row[0]= viewDrug.get(i).getPrescriptionID();
                row[1] = viewDrug.get(i).getDrugName();
                row[2] = viewDrug.get(i).getDosage();
                row[3] = viewDrug.get(i).getFrequency();
                row[4] = viewDrug.get(i).getPeroid();
                                
                model.addRow(row);
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prescTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        drugTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        searchbtn = new javax.swing.JButton();
        drugSearch = new javax.swing.JButton();
        prescriptionID = new javax.swing.JTextField();
        prescDateField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Prescription Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 233, 29);

        prescTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Prescription ID", "Patient name", "Age", "Create date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(prescTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 171, 518, 402);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Drug Stock Details");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(598, 11, 221, 29);

        drugTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Prescription ID", "Drug name", "Dosage", "Frequency", "Period"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(drugTable);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(598, 171, 601, 402);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Dispense");
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 616, 103, 31);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        searchbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        drugSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        drugSearch.setText("Search");
        drugSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugSearchActionPerformed(evt);
            }
        });

        prescriptionID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Patient Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Prescription ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(prescDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(prescriptionID, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(drugSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(prescDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchbtn)
                            .addComponent(jLabel6)
                            .addComponent(prescriptionID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drugSearch))))
                .addGap(969, 969, 969))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        try {
            searchResultList = null;
            searchResultList = new ArrayList(PrescriptionController.getPresc().searchDateDetails(prescDateField.getText()));
            if (searchResultList != null) {
                model = (DefaultTableModel) prescTable.getModel();
                    //Removing all the rows in the jTable
                int rowCount = model.getRowCount();
                for (int i = rowCount - 1; i >= 0; i--) {
                    model.removeRow(i);
                }
                    for (Prescription pres : searchResultList) {
                        model.addRow(new Object[]{pres.getPrescriptionID(), pres.getPatientName(), pres.getAge(), pres.getCreateDate()});
                    }
            }
            
        } catch (SQLException ex) {
            //messageAlert.getMessageAlert(DBUtil.getXMLData("PatientMsg", "message", "Err_Something_Went_Wrong"), "error");
            //LOG.error(ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(PrescView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void drugSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugSearchActionPerformed
        try {
            drugSearchResults = null;
            drugSearchResults = new ArrayList(PrescriptionController.getPresc().searchPrescIdDetails(Integer.parseInt(prescriptionID.getText())));
            if (drugSearchResults != null) {
                model = (DefaultTableModel) drugTable.getModel();
                    //Removing all the rows in the jTable
                int rowCount = model.getRowCount();
                for (int i = rowCount - 1; i >= 0; i--) {
                    model.removeRow(i);
                }
                    for (Prescription pres : drugSearchResults) {
                        model.addRow(new Object[]{pres.getPrescriptionID(), pres.getDrugName(), pres.getDosage(), pres.getFrequency(), pres.getPeroid()});
                    }
            }
            
        } catch (SQLException ex) {
            //messageAlert.getMessageAlert(DBUtil.getXMLData("PatientMsg", "message", "Err_Something_Went_Wrong"), "error");
            //LOG.error(ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(PrescView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_drugSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrescView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrescView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrescView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrescView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PrescView().setVisible(true);
                } catch (IOException ex) {
                
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton drugSearch;
    private javax.swing.JTable drugTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField prescDateField;
    private javax.swing.JTable prescTable;
    private javax.swing.JTextField prescriptionID;
    private javax.swing.JButton searchbtn;
    // End of variables declaration//GEN-END:variables
}
