/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.layout.stockManagement;

import Controller.StockManagement.DrugCategoryController;
import java.sql.SQLException;
import model.DrugCategoryModel;
import org.apache.log4j.Logger;
import util.Config;
import static util.DBUtil.getXMLData;
import static util.Util.getScreenSizrRatio;
import static util.messageAlert.getMessageAlert;

/**
 *
 * @author EnTeRs
 */
public class AddDrugCategory extends javax.swing.JFrame {

    private static AddDrugCategory self;

    static int ScreenW = (int) getScreenSizrRatio()[0];
    static int ScreenH = (int) getScreenSizrRatio()[1];

    Config cnf = new Config();
    public Logger LOG;

    public AddDrugCategory() {
        initComponents();
        self = this;
        this.setLocation((ScreenW - this.getWidth()) / 2,
                (ScreenH - this.getHeight()) / 2);

        //initialize log file
        LOG = cnf.getLogger(AddDrugCategory.class);
    }

    public static AddDrugCategory getInstance() {
        if (self == null) {
            self = new AddDrugCategory();
        }

        return self;
    }

    public final void resetJframe() {
        util.Util.Clear(AddDrugCategoryPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddDrugCategoryPanel = new javax.swing.JPanel();
        adcTitleLabel = new javax.swing.JLabel();
        adcDrugCatNameLabel = new javax.swing.JLabel();
        adcAddNewBtn = new javax.swing.JButton();
        adcCloseBtn = new javax.swing.JButton();
        adcDrugCatNameInput = new javax.swing.JTextField();
        adcDrugCatDescLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adcDrugCatDescInput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(800, 400));
        setMinimumSize(new java.awt.Dimension(800, 400));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 400));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        AddDrugCategoryPanel.setBackground(new java.awt.Color(0, 0, 0));
        AddDrugCategoryPanel.setMaximumSize(new java.awt.Dimension(800, 400));
        AddDrugCategoryPanel.setMinimumSize(new java.awt.Dimension(800, 400));
        AddDrugCategoryPanel.setPreferredSize(new java.awt.Dimension(800, 400));
        AddDrugCategoryPanel.setLayout(null);

        adcTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        adcTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        adcTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adcTitleLabel.setText("Add New Drug Category");
        AddDrugCategoryPanel.add(adcTitleLabel);
        adcTitleLabel.setBounds(0, 30, 800, 50);

        adcDrugCatNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adcDrugCatNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        adcDrugCatNameLabel.setText("Drug Category Name");
        AddDrugCategoryPanel.add(adcDrugCatNameLabel);
        adcDrugCatNameLabel.setBounds(120, 140, 180, 30);

        adcAddNewBtn.setText("Add New");
        adcAddNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adcAddNewBtnActionPerformed(evt);
            }
        });
        AddDrugCategoryPanel.add(adcAddNewBtn);
        adcAddNewBtn.setBounds(300, 310, 200, 40);

        adcCloseBtn.setText("X");
        adcCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adcCloseBtnActionPerformed(evt);
            }
        });
        AddDrugCategoryPanel.add(adcCloseBtn);
        adcCloseBtn.setBounds(740, 10, 40, 40);
        AddDrugCategoryPanel.add(adcDrugCatNameInput);
        adcDrugCatNameInput.setBounds(310, 140, 300, 30);

        adcDrugCatDescLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adcDrugCatDescLabel.setForeground(new java.awt.Color(255, 255, 255));
        adcDrugCatDescLabel.setText("Description");
        AddDrugCategoryPanel.add(adcDrugCatDescLabel);
        adcDrugCatDescLabel.setBounds(120, 200, 180, 30);

        adcDrugCatDescInput.setColumns(20);
        adcDrugCatDescInput.setRows(3);
        jScrollPane1.setViewportView(adcDrugCatDescInput);

        AddDrugCategoryPanel.add(jScrollPane1);
        jScrollPane1.setBounds(310, 200, 300, 70);

        getContentPane().add(AddDrugCategoryPanel);
        AddDrugCategoryPanel.setBounds(0, 0, 800, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adcAddNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adcAddNewBtnActionPerformed
        try {
            DrugCategoryModel drugCategory = new DrugCategoryModel(adcDrugCatNameInput.getText(), adcDrugCatDescInput.getText());
            DrugCategoryController.getInstance().save(drugCategory);
            AddDrugItem.getInstance().getCategoriesInit();
            AddDrugItem.getInstance().asiDrugCatVali.setVisible(false);
            getMessageAlert(String.format(getXMLData("StockMsg", "message", "addedMsg"), "Drug Category"), "success");
            resetJframe();
        } catch (SQLException ex) {
            getMessageAlert(getXMLData("StockMsg", "message", "somethingWrong"), "error");
            LOG.error(ex);
        }
    }//GEN-LAST:event_adcAddNewBtnActionPerformed

    private void adcCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adcCloseBtnActionPerformed
        dispose();
    }//GEN-LAST:event_adcCloseBtnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        AddDrugItem.getInstance().setEnabled(true);
        AddDrugItem.getInstance().toFront();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDrugCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDrugCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDrugCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDrugCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDrugCategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddDrugCategoryPanel;
    private javax.swing.JButton adcAddNewBtn;
    private javax.swing.JButton adcCloseBtn;
    private javax.swing.JTextArea adcDrugCatDescInput;
    private javax.swing.JLabel adcDrugCatDescLabel;
    private javax.swing.JTextField adcDrugCatNameInput;
    private javax.swing.JLabel adcDrugCatNameLabel;
    private javax.swing.JLabel adcTitleLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
