/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.layout.stockManagement;

/**
 *
 * @author EnTeRs
 */
public class DrugList extends javax.swing.JFrame {

    /**
     * Creates new form AddStockItem
     */
    public DrugList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddStockItemPanel = new javax.swing.JPanel();
        dlTitleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dlDrugTable = new javax.swing.JTable();
        dlSearchLabel = new javax.swing.JLabel();
        dlSearchInput = new javax.swing.JTextField();
        dlSearchTypeCheckbox = new javax.swing.JCheckBox();
        dlSearchNameCheckbox = new javax.swing.JCheckBox();
        dlSearchCategoryCheckbox = new javax.swing.JCheckBox();
        slDownloadQtyReportBtn = new javax.swing.JButton();
        dlDownloadFullReportBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1765, 770));
        getContentPane().setLayout(null);

        AddStockItemPanel.setBackground(new java.awt.Color(0, 0, 0));
        AddStockItemPanel.setMaximumSize(new java.awt.Dimension(1765, 770));
        AddStockItemPanel.setMinimumSize(new java.awt.Dimension(1765, 770));
        AddStockItemPanel.setLayout(null);

        dlTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        dlTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        dlTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dlTitleLabel.setText("Drug List");
        AddStockItemPanel.add(dlTitleLabel);
        dlTitleLabel.setBounds(0, 30, 1760, 50);

        dlDrugTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Category", "Type", "Price(Rs.)", "Remarks", "Danger Level", "Reorder Level", "Weight", "Qty.", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dlDrugTable);
        if (dlDrugTable.getColumnModel().getColumnCount() > 0) {
            dlDrugTable.getColumnModel().getColumn(0).setMinWidth(20);
            dlDrugTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            dlDrugTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            dlDrugTable.getColumnModel().getColumn(3).setPreferredWidth(30);
            dlDrugTable.getColumnModel().getColumn(4).setPreferredWidth(25);
            dlDrugTable.getColumnModel().getColumn(6).setPreferredWidth(25);
            dlDrugTable.getColumnModel().getColumn(7).setPreferredWidth(25);
            dlDrugTable.getColumnModel().getColumn(8).setPreferredWidth(50);
            dlDrugTable.getColumnModel().getColumn(9).setPreferredWidth(25);
        }

        AddStockItemPanel.add(jScrollPane1);
        jScrollPane1.setBounds(30, 180, 1710, 480);

        dlSearchLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dlSearchLabel.setForeground(new java.awt.Color(255, 255, 255));
        dlSearchLabel.setText("Search");
        AddStockItemPanel.add(dlSearchLabel);
        dlSearchLabel.setBounds(30, 120, 120, 30);

        dlSearchInput.setText("jTextField1");
        AddStockItemPanel.add(dlSearchInput);
        dlSearchInput.setBounds(160, 120, 300, 30);

        dlSearchTypeCheckbox.setBackground(new java.awt.Color(0, 0, 0));
        dlSearchTypeCheckbox.setForeground(new java.awt.Color(255, 255, 255));
        dlSearchTypeCheckbox.setText("Type");
        AddStockItemPanel.add(dlSearchTypeCheckbox);
        dlSearchTypeCheckbox.setBounds(700, 120, 90, 30);

        dlSearchNameCheckbox.setBackground(new java.awt.Color(0, 0, 0));
        dlSearchNameCheckbox.setForeground(new java.awt.Color(255, 255, 255));
        dlSearchNameCheckbox.setText("Name");
        AddStockItemPanel.add(dlSearchNameCheckbox);
        dlSearchNameCheckbox.setBounds(500, 120, 80, 30);

        dlSearchCategoryCheckbox.setBackground(new java.awt.Color(0, 0, 0));
        dlSearchCategoryCheckbox.setForeground(new java.awt.Color(255, 255, 255));
        dlSearchCategoryCheckbox.setText("Category");
        AddStockItemPanel.add(dlSearchCategoryCheckbox);
        dlSearchCategoryCheckbox.setBounds(590, 120, 90, 30);

        slDownloadQtyReportBtn.setText("Download Quantity Report");
        AddStockItemPanel.add(slDownloadQtyReportBtn);
        slDownloadQtyReportBtn.setBounds(1300, 690, 200, 40);

        dlDownloadFullReportBtn.setText("Download Full Report");
        AddStockItemPanel.add(dlDownloadFullReportBtn);
        dlDownloadFullReportBtn.setBounds(1530, 690, 200, 40);

        getContentPane().add(AddStockItemPanel);
        AddStockItemPanel.setBounds(0, 0, 1765, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrugList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrugList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrugList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrugList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrugList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddStockItemPanel;
    private javax.swing.JButton dlDownloadFullReportBtn;
    private javax.swing.JTable dlDrugTable;
    private javax.swing.JCheckBox dlSearchCategoryCheckbox;
    private javax.swing.JTextField dlSearchInput;
    private javax.swing.JLabel dlSearchLabel;
    private javax.swing.JCheckBox dlSearchNameCheckbox;
    private javax.swing.JCheckBox dlSearchTypeCheckbox;
    private javax.swing.JLabel dlTitleLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton slDownloadQtyReportBtn;
    // End of variables declaration//GEN-END:variables
}
