/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.layout.stockManagement;

/**
 *
 * @author EnTeRs
 */
public class SupplierDetails extends javax.swing.JFrame {

    /**
     * Creates new form AddStockItem
     */
    public SupplierDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SupplierDetailsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sdSupplierTable = new javax.swing.JTable();
        sdSupplierNameLabel = new javax.swing.JLabel();
        sdSupplierNameInput = new javax.swing.JTextField();
        sdTitleLabel = new javax.swing.JLabel();
        sdSupplierAddressLabel = new javax.swing.JLabel();
        sdSupplierAddressInput = new javax.swing.JTextField();
        sdSupplierContactLabel = new javax.swing.JLabel();
        sdSupplierContactInput = new javax.swing.JTextField();
        sdSupplierEmailInput = new javax.swing.JTextField();
        sdSupplierEmailLabel = new javax.swing.JLabel();
        sdUpdateBtn = new javax.swing.JButton();
        sdRemoveBtn = new javax.swing.JButton();
        sdSupplierNameLabel1 = new javax.swing.JLabel();
        sdSupplierNameInput1 = new javax.swing.JTextField();
        sdAddBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1765, 770));
        getContentPane().setLayout(null);

        SupplierDetailsPanel.setBackground(new java.awt.Color(0, 0, 0));
        SupplierDetailsPanel.setMaximumSize(new java.awt.Dimension(1765, 770));
        SupplierDetailsPanel.setMinimumSize(new java.awt.Dimension(1765, 770));
        SupplierDetailsPanel.setLayout(null);

        sdSupplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "Contact", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(sdSupplierTable);
        if (sdSupplierTable.getColumnModel().getColumnCount() > 0) {
            sdSupplierTable.getColumnModel().getColumn(0).setMinWidth(20);
            sdSupplierTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        SupplierDetailsPanel.add(jScrollPane1);
        jScrollPane1.setBounds(550, 140, 1190, 540);

        sdSupplierNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sdSupplierNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        sdSupplierNameLabel.setText("Supplier Name");
        SupplierDetailsPanel.add(sdSupplierNameLabel);
        sdSupplierNameLabel.setBounds(50, 250, 130, 30);

        sdSupplierNameInput.setText("jTextField1");
        SupplierDetailsPanel.add(sdSupplierNameInput);
        sdSupplierNameInput.setBounds(190, 250, 300, 30);

        sdTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        sdTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        sdTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sdTitleLabel.setText("Supplier Details");
        SupplierDetailsPanel.add(sdTitleLabel);
        sdTitleLabel.setBounds(0, 30, 1760, 50);

        sdSupplierAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sdSupplierAddressLabel.setForeground(new java.awt.Color(255, 255, 255));
        sdSupplierAddressLabel.setText("Address");
        SupplierDetailsPanel.add(sdSupplierAddressLabel);
        sdSupplierAddressLabel.setBounds(50, 320, 130, 30);

        sdSupplierAddressInput.setText("jTextField1");
        SupplierDetailsPanel.add(sdSupplierAddressInput);
        sdSupplierAddressInput.setBounds(190, 320, 300, 30);

        sdSupplierContactLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sdSupplierContactLabel.setForeground(new java.awt.Color(255, 255, 255));
        sdSupplierContactLabel.setText("Contact No.");
        SupplierDetailsPanel.add(sdSupplierContactLabel);
        sdSupplierContactLabel.setBounds(50, 390, 130, 30);

        sdSupplierContactInput.setText("jTextField1");
        SupplierDetailsPanel.add(sdSupplierContactInput);
        sdSupplierContactInput.setBounds(190, 390, 300, 30);

        sdSupplierEmailInput.setText("jTextField1");
        SupplierDetailsPanel.add(sdSupplierEmailInput);
        sdSupplierEmailInput.setBounds(190, 460, 300, 30);

        sdSupplierEmailLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sdSupplierEmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        sdSupplierEmailLabel.setText("Email");
        SupplierDetailsPanel.add(sdSupplierEmailLabel);
        sdSupplierEmailLabel.setBounds(50, 460, 130, 30);

        sdUpdateBtn.setText("Update");
        SupplierDetailsPanel.add(sdUpdateBtn);
        sdUpdateBtn.setBounds(290, 550, 200, 40);

        sdRemoveBtn.setText("Remove");
        SupplierDetailsPanel.add(sdRemoveBtn);
        sdRemoveBtn.setBounds(170, 620, 200, 40);

        sdSupplierNameLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sdSupplierNameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        sdSupplierNameLabel1.setText("Supplier Id");
        SupplierDetailsPanel.add(sdSupplierNameLabel1);
        sdSupplierNameLabel1.setBounds(50, 180, 130, 30);

        sdSupplierNameInput1.setEditable(false);
        sdSupplierNameInput1.setText("jTextField1");
        SupplierDetailsPanel.add(sdSupplierNameInput1);
        sdSupplierNameInput1.setBounds(190, 180, 300, 30);

        sdAddBtn.setText("Add New");
        SupplierDetailsPanel.add(sdAddBtn);
        sdAddBtn.setBounds(50, 550, 200, 40);

        getContentPane().add(SupplierDetailsPanel);
        SupplierDetailsPanel.setBounds(0, 0, 1765, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SupplierDetailsPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sdAddBtn;
    private javax.swing.JButton sdRemoveBtn;
    private javax.swing.JTextField sdSupplierAddressInput;
    private javax.swing.JLabel sdSupplierAddressLabel;
    private javax.swing.JTextField sdSupplierContactInput;
    private javax.swing.JLabel sdSupplierContactLabel;
    private javax.swing.JTextField sdSupplierEmailInput;
    private javax.swing.JLabel sdSupplierEmailLabel;
    private javax.swing.JTextField sdSupplierNameInput;
    private javax.swing.JTextField sdSupplierNameInput1;
    private javax.swing.JLabel sdSupplierNameLabel;
    private javax.swing.JLabel sdSupplierNameLabel1;
    private javax.swing.JTable sdSupplierTable;
    private javax.swing.JLabel sdTitleLabel;
    private javax.swing.JButton sdUpdateBtn;
    // End of variables declaration//GEN-END:variables
}
