/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.layout.stockManagement;

/**
 *
 * @author EnTeRs
 */
public class UpdateDrugItem extends javax.swing.JFrame {

    /**
     * Creates new form AddStockItem
     */
    public UpdateDrugItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateDrugItemPanel = new javax.swing.JPanel();
        udiTitleLabel = new javax.swing.JLabel();
        udiDrugCategoryLabel = new javax.swing.JLabel();
        udiDrugCategorySelector = new javax.swing.JComboBox<>();
        udiDrugNameLabel = new javax.swing.JLabel();
        udiDrugNameInput = new javax.swing.JTextField();
        udiDrugTypeLabel = new javax.swing.JLabel();
        udiDrugTypeSelector = new javax.swing.JComboBox<>();
        udiDrugPriceLabel = new javax.swing.JLabel();
        udiDrugPriceInput = new javax.swing.JTextField();
        udiRemarksInput = new javax.swing.JTextField();
        udiRemarksLabel = new javax.swing.JLabel();
        udiDrugLevelInput = new javax.swing.JSpinner();
        udiDrugLevelLabel = new javax.swing.JLabel();
        udiReorderLevelInput = new javax.swing.JSpinner();
        udiReorderLevelLabel = new javax.swing.JLabel();
        udiDrugWeightInput = new javax.swing.JTextField();
        udiResetBtn = new javax.swing.JButton();
        udiInsertBtn = new javax.swing.JButton();
        udiDrugWeightLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        udiFormErrors = new javax.swing.JTextArea();
        asiAddCatBtn = new javax.swing.JButton();
        asiUpdateRemoveCatBtn = new javax.swing.JButton();
        asiAddTypeBtn = new javax.swing.JButton();
        asiUpdateRemoveTypeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1765, 770));
        getContentPane().setLayout(null);

        UpdateDrugItemPanel.setBackground(new java.awt.Color(0, 0, 0));
        UpdateDrugItemPanel.setMaximumSize(new java.awt.Dimension(1765, 770));
        UpdateDrugItemPanel.setMinimumSize(new java.awt.Dimension(1765, 770));
        UpdateDrugItemPanel.setLayout(null);

        udiTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        udiTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        udiTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        udiTitleLabel.setText("Update Drug");
        UpdateDrugItemPanel.add(udiTitleLabel);
        udiTitleLabel.setBounds(0, 30, 1760, 50);

        udiDrugCategoryLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        udiDrugCategoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        udiDrugCategoryLabel.setText("Drug Category");
        UpdateDrugItemPanel.add(udiDrugCategoryLabel);
        udiDrugCategoryLabel.setBounds(160, 170, 200, 30);

        udiDrugCategorySelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        UpdateDrugItemPanel.add(udiDrugCategorySelector);
        udiDrugCategorySelector.setBounds(380, 170, 300, 30);

        udiDrugNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        udiDrugNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        udiDrugNameLabel.setText("Drug Name");
        UpdateDrugItemPanel.add(udiDrugNameLabel);
        udiDrugNameLabel.setBounds(160, 240, 200, 30);

        udiDrugNameInput.setText("jTextField1");
        UpdateDrugItemPanel.add(udiDrugNameInput);
        udiDrugNameInput.setBounds(380, 240, 300, 30);

        udiDrugTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        udiDrugTypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        udiDrugTypeLabel.setText("Drug Type");
        UpdateDrugItemPanel.add(udiDrugTypeLabel);
        udiDrugTypeLabel.setBounds(160, 310, 200, 30);

        udiDrugTypeSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        UpdateDrugItemPanel.add(udiDrugTypeSelector);
        udiDrugTypeSelector.setBounds(380, 310, 300, 30);

        udiDrugPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        udiDrugPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        udiDrugPriceLabel.setText("Drug Price");
        UpdateDrugItemPanel.add(udiDrugPriceLabel);
        udiDrugPriceLabel.setBounds(160, 380, 200, 30);

        udiDrugPriceInput.setText("jTextField1");
        UpdateDrugItemPanel.add(udiDrugPriceInput);
        udiDrugPriceInput.setBounds(380, 380, 300, 30);

        udiRemarksInput.setText("jTextField1");
        UpdateDrugItemPanel.add(udiRemarksInput);
        udiRemarksInput.setBounds(1310, 170, 300, 30);

        udiRemarksLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        udiRemarksLabel.setForeground(new java.awt.Color(255, 255, 255));
        udiRemarksLabel.setText("Remarks");
        UpdateDrugItemPanel.add(udiRemarksLabel);
        udiRemarksLabel.setBounds(1090, 170, 200, 30);
        UpdateDrugItemPanel.add(udiDrugLevelInput);
        udiDrugLevelInput.setBounds(1310, 240, 300, 30);

        udiDrugLevelLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        udiDrugLevelLabel.setForeground(new java.awt.Color(255, 255, 255));
        udiDrugLevelLabel.setText("Drug Level");
        UpdateDrugItemPanel.add(udiDrugLevelLabel);
        udiDrugLevelLabel.setBounds(1090, 240, 200, 30);
        UpdateDrugItemPanel.add(udiReorderLevelInput);
        udiReorderLevelInput.setBounds(1310, 310, 300, 30);

        udiReorderLevelLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        udiReorderLevelLabel.setForeground(new java.awt.Color(255, 255, 255));
        udiReorderLevelLabel.setText("Reorder Level");
        UpdateDrugItemPanel.add(udiReorderLevelLabel);
        udiReorderLevelLabel.setBounds(1090, 310, 200, 30);

        udiDrugWeightInput.setText("jTextField1");
        UpdateDrugItemPanel.add(udiDrugWeightInput);
        udiDrugWeightInput.setBounds(1310, 380, 300, 30);

        udiResetBtn.setText("Reset");
        UpdateDrugItemPanel.add(udiResetBtn);
        udiResetBtn.setBounds(900, 670, 200, 40);

        udiInsertBtn.setText("Insert");
        UpdateDrugItemPanel.add(udiInsertBtn);
        udiInsertBtn.setBounds(620, 670, 200, 40);

        udiDrugWeightLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        udiDrugWeightLabel1.setForeground(new java.awt.Color(255, 255, 255));
        udiDrugWeightLabel1.setText("Drug Weight");
        UpdateDrugItemPanel.add(udiDrugWeightLabel1);
        udiDrugWeightLabel1.setBounds(1090, 380, 200, 30);

        udiFormErrors.setEditable(false);
        udiFormErrors.setBackground(new java.awt.Color(0, 0, 0));
        udiFormErrors.setColumns(20);
        udiFormErrors.setFont(new java.awt.Font("Getone-Reg", 0, 13)); // NOI18N
        udiFormErrors.setForeground(new java.awt.Color(255, 0, 0));
        udiFormErrors.setRows(5);
        udiFormErrors.setText("dfgdfhsfhdfhdhd");
        udiFormErrors.setBorder(null);
        jScrollPane1.setViewportView(udiFormErrors);

        UpdateDrugItemPanel.add(jScrollPane1);
        jScrollPane1.setBounds(620, 476, 480, 120);

        asiAddCatBtn.setText("Add New");
        UpdateDrugItemPanel.add(asiAddCatBtn);
        asiAddCatBtn.setBounds(710, 170, 90, 30);

        asiUpdateRemoveCatBtn.setText("Update/Remove Selected");
        UpdateDrugItemPanel.add(asiUpdateRemoveCatBtn);
        asiUpdateRemoveCatBtn.setBounds(810, 170, 190, 30);

        asiAddTypeBtn.setText("Add New");
        UpdateDrugItemPanel.add(asiAddTypeBtn);
        asiAddTypeBtn.setBounds(710, 310, 90, 30);

        asiUpdateRemoveTypeBtn.setText("Update/Remove Selected");
        UpdateDrugItemPanel.add(asiUpdateRemoveTypeBtn);
        asiUpdateRemoveTypeBtn.setBounds(810, 310, 190, 30);

        getContentPane().add(UpdateDrugItemPanel);
        UpdateDrugItemPanel.setBounds(0, 0, 1765, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDrugItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDrugItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDrugItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDrugItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDrugItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UpdateDrugItemPanel;
    private javax.swing.JButton asiAddCatBtn;
    private javax.swing.JButton asiAddTypeBtn;
    private javax.swing.JButton asiUpdateRemoveCatBtn;
    private javax.swing.JButton asiUpdateRemoveTypeBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel udiDrugCategoryLabel;
    private javax.swing.JComboBox<String> udiDrugCategorySelector;
    private javax.swing.JSpinner udiDrugLevelInput;
    private javax.swing.JLabel udiDrugLevelLabel;
    private javax.swing.JTextField udiDrugNameInput;
    private javax.swing.JLabel udiDrugNameLabel;
    private javax.swing.JTextField udiDrugPriceInput;
    private javax.swing.JLabel udiDrugPriceLabel;
    private javax.swing.JLabel udiDrugTypeLabel;
    private javax.swing.JComboBox<String> udiDrugTypeSelector;
    private javax.swing.JTextField udiDrugWeightInput;
    private javax.swing.JLabel udiDrugWeightLabel1;
    private javax.swing.JTextArea udiFormErrors;
    private javax.swing.JButton udiInsertBtn;
    private javax.swing.JTextField udiRemarksInput;
    private javax.swing.JLabel udiRemarksLabel;
    private javax.swing.JSpinner udiReorderLevelInput;
    private javax.swing.JLabel udiReorderLevelLabel;
    private javax.swing.JButton udiResetBtn;
    private javax.swing.JLabel udiTitleLabel;
    // End of variables declaration//GEN-END:variables
}
