/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.layout.stockManagement;

/**
 *
 * @author EnTeRs
 */
public class UpdateRemoveDrugType extends javax.swing.JFrame {

    /**
     * Creates new form AddStockItem
     */
    public UpdateRemoveDrugType() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateRemoveDrugTypePanel = new javax.swing.JPanel();
        urdtTitleLabel = new javax.swing.JLabel();
        urdtDrugCatNameLabel = new javax.swing.JLabel();
        urdtUpdateBtn = new javax.swing.JButton();
        urdcCloseBtn = new javax.swing.JButton();
        urdtDrugCatNameInput = new javax.swing.JTextField();
        urdtRemoveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 300));
        getContentPane().setLayout(null);

        UpdateRemoveDrugTypePanel.setBackground(new java.awt.Color(0, 0, 0));
        UpdateRemoveDrugTypePanel.setMaximumSize(new java.awt.Dimension(800, 300));
        UpdateRemoveDrugTypePanel.setMinimumSize(new java.awt.Dimension(800, 300));
        UpdateRemoveDrugTypePanel.setLayout(null);

        urdtTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        urdtTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        urdtTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        urdtTitleLabel.setText("Update/Remove Drug Type");
        UpdateRemoveDrugTypePanel.add(urdtTitleLabel);
        urdtTitleLabel.setBounds(0, 30, 800, 50);

        urdtDrugCatNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        urdtDrugCatNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        urdtDrugCatNameLabel.setText("Drug Type Name");
        UpdateRemoveDrugTypePanel.add(urdtDrugCatNameLabel);
        urdtDrugCatNameLabel.setBounds(120, 140, 180, 30);

        urdtUpdateBtn.setText("Update");
        UpdateRemoveDrugTypePanel.add(urdtUpdateBtn);
        urdtUpdateBtn.setBounds(230, 220, 140, 40);

        urdcCloseBtn.setText("X");
        urdcCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urdcCloseBtnActionPerformed(evt);
            }
        });
        UpdateRemoveDrugTypePanel.add(urdcCloseBtn);
        urdcCloseBtn.setBounds(740, 10, 40, 40);
        UpdateRemoveDrugTypePanel.add(urdtDrugCatNameInput);
        urdtDrugCatNameInput.setBounds(310, 140, 300, 30);

        urdtRemoveBtn.setText("Remove");
        UpdateRemoveDrugTypePanel.add(urdtRemoveBtn);
        urdtRemoveBtn.setBounds(410, 220, 140, 40);

        getContentPane().add(UpdateRemoveDrugTypePanel);
        UpdateRemoveDrugTypePanel.setBounds(0, 0, 800, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urdcCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urdcCloseBtnActionPerformed
        dispose();
    }//GEN-LAST:event_urdcCloseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateRemoveDrugType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateRemoveDrugType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateRemoveDrugType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateRemoveDrugType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateRemoveDrugType().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UpdateRemoveDrugTypePanel;
    private javax.swing.JButton urdcCloseBtn;
    private javax.swing.JTextField urdtDrugCatNameInput;
    private javax.swing.JLabel urdtDrugCatNameLabel;
    private javax.swing.JButton urdtRemoveBtn;
    private javax.swing.JLabel urdtTitleLabel;
    private javax.swing.JButton urdtUpdateBtn;
    // End of variables declaration//GEN-END:variables
}
